/**
 * Resolve static MP3 paths generated by `npm run audio:edge-tts`
 * from public/data/tu-vung-n2.json and ngu-phap-n2.json (server-side only).
 */

import * as fs from 'fs';
import * as path from 'path';

const DATA_DIR = path.join(process.cwd(), 'public', 'data');

let vocabMap: Map<string, string> | null = null;
let grammarPatterns: Array<{
  stt: number;
  mau_ngu_phap: unknown;
  vi_du: string[];
}> | null = null;
let readingItems: Array<{
  passage?: { title?: string };
  vocabulary?: Array<{ word?: string }>;
}> | null = null;

function vocabKey(word: string, reading: string) {
  return `${word.trim()}\0${reading.trim()}`;
}

function loadVocabMap(): Map<string, string> {
  if (vocabMap) return vocabMap;
  const raw = JSON.parse(
    fs.readFileSync(path.join(DATA_DIR, 'tu-vung-n2.json'), 'utf8'),
  ) as { vocabulary?: Array<{ stt: number; kanji: string; hiragana?: string }> };
  const m = new Map<string, string>();
  for (const v of raw.vocabulary ?? []) {
    const kanji = (v.kanji ?? '').trim();
    const h = (v.hiragana ?? '').trim();
    m.set(
      vocabKey(kanji, h),
      `/audio/tu-vung-n2/v-${String(v.stt).padStart(4, '0')}.mp3`,
    );
  }
  vocabMap = m;
  return m;
}

function firstMau(p: { mau_ngu_phap: unknown }) {
  const m = p.mau_ngu_phap;
  return Array.isArray(m) ? String(m[0] ?? '').trim() : String(m ?? '').trim();
}

function loadGrammarPatterns() {
  if (grammarPatterns) return grammarPatterns;
  const raw = JSON.parse(
    fs.readFileSync(path.join(DATA_DIR, 'ngu-phap-n2.json'), 'utf8'),
  ) as {
    patterns?: Array<{ stt: number; mau_ngu_phap: unknown; vi_du: string[] }>;
  };
  grammarPatterns = raw.patterns ?? [];
  return grammarPatterns;
}

function loadReadingItems() {
  if (readingItems) return readingItems;
  const raw = JSON.parse(
    fs.readFileSync(path.join(DATA_DIR, 'reading-n2.json'), 'utf8'),
  ) as Array<{
    passage?: { title?: string };
    vocabulary?: Array<{ word?: string }>;
  }>;
  readingItems = Array.isArray(raw) ? raw : [];
  return readingItems;
}

/** Hiragana reading MP3 from Mimikara N2 JSON (matches seed: word=kanji, reading=hiragana). */
export function getN2VocabAudioSrc(
  word: string,
  reading: string | null | undefined,
): string | undefined {
  return loadVocabMap().get(vocabKey(word, reading ?? ''));
}

/** Example sentence MP3; matches grammar.title to mau_ngu_phap[0] and exampleJp to vi_du entry. */
export function getN2GrammarExampleAudioSrc(
  title: string,
  exampleJp: string | null | undefined,
): string | undefined {
  if (!exampleJp?.trim()) return undefined;
  const ps = loadGrammarPatterns();
  const p = ps.find((pat) => firstMau(pat) === title.trim());
  if (!p) return undefined;
  const vi = p.vi_du ?? [];
  const idx = vi.findIndex((s) => s.trim() === exampleJp.trim());
  const i = idx >= 0 ? idx : 0;
  return `/audio/ngu-phap-n2/gp-${String(p.stt).padStart(3, '0')}-${i}.mp3`;
}

export function attachN2VocabAudio<T extends { word: string; reading: string | null }>(
  items: T[],
): (T & { n2AudioSrc?: string })[] {
  return items.map((item) => {
    const n2AudioSrc = getN2VocabAudioSrc(item.word, item.reading);
    return n2AudioSrc ? { ...item, n2AudioSrc } : { ...item };
  });
}

/** Reading vocab word MP3 by passage title + row index in vocabulary table. */
export function getReadingVocabAudioSrc(
  passageTitle: string,
  vocabIndex: number,
): string | undefined {
  if (!passageTitle.trim() || vocabIndex < 0) return undefined;
  const items = loadReadingItems();
  const passageIdx = items.findIndex(
    (item) => (item.passage?.title ?? '').trim() === passageTitle.trim(),
  );
  if (passageIdx < 0) return undefined;
  const rows = items[passageIdx]?.vocabulary ?? [];
  if (vocabIndex >= rows.length) return undefined;
  return `/audio/reading-n2/rd-${String(passageIdx + 1).padStart(3, '0')}-${String(vocabIndex).padStart(3, '0')}.mp3`;
}
